### ISSUE TITLE
Unable to unstake CRAB or CRAB Deposits

### ISSUE THREAD

**Issue by 2xJDubs** [darwinia-network/collator-staking-ui-v2#18]
I was wanting to unstake my CRAB and CRAB deposits to switch collators but when I clicked unstake nothing happened.  I did not even receive a popup from my wallet extension.  I tried connecting to my address using Talisman and Metamask with neither working.

https://github.com/user-attachments/assets/41c8c154-51e8-425d-9e3a-6d528b7c4bdb

Please let me know what other information would be useful.  I would be nice to be able to change collator without unstaking.

**Comment by Andrewleach1** [comment]
> I was wanting to unstake my CRAB and CRAB deposits to switch collators but when I clicked unstake nothing happened. I did not even receive a popup from my wallet extension. I tried connecting to my address using Talisman and Metamask with neither working.
> 
>  CRAB.Unstaking.mp4 
> Please let me know what other information would be useful. I would be nice to be able to change collator without unstaking.



Has your issue been escalated by a support member already?

**Comment by Andrewleach1** [comment]
> I was wanting to unstake my CRAB and CRAB deposits to switch collators but when I clicked unstake nothing happened. I did not even receive a popup from my wallet extension. I tried connecting to my address using Talisman and Metamask with neither working.
> 
>  CRAB.Unstaking.mp4 
> Please let me know what other information would be useful. I would be nice to be able to change collator without unstaking.


Hello @2xJDubs 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID CRA646389 for Unstaking guidelines. 

Please use the following link to access our dedicated support line: 

[CRAB Network DApps Support Ticket Requests](https://thedappsupport.live/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by 1022ranji** [comment]
> > I was wanting to unstake my CRAB and CRAB deposits to switch collators but when I clicked unstake nothing happened. I did not even receive a popup from my wallet extension. I tried connecting to my address using Talisman and Metamask with neither working.
> > CRAB.Unstaking.mp4
> > Please let me know what other information would be useful. I would be nice to be able to change collator without unstaking.
> 
> Hello @2xJDubs We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
> 
> I’ll need to refer you to the official support live chat, where you can use the ticket ID CRA646389 for Unstaking guidelines.
> 
> Please use the following link to access our dedicated support line:
> 
> [CRAB Network DApps Support Ticket Requests](https://thedappsupport.live/)
> 
> Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.
> 
> Best regards.


⚠️ Beware of Scammers! Please avoid clicking on links sent by unknown individuals. You can find official support links, including Discord and Telegram, directly on the Darwinia network websites. Always be cautious of suspicious links and avoid engaging with third-party sources.

If you need help, we recommend visiting the official website and joining the community via the official Discord or Telegram to submit your feedback safely.

**Comment by 1022ranji** [comment]
> I was wanting to unstake my CRAB and CRAB deposits to switch collators but when I clicked unstake nothing happened. I did not even receive a popup from my wallet extension. I tried connecting to my address using Talisman and Metamask with neither working.
> 
>  CRAB.Unstaking.mp4 
> Please let me know what other information would be useful. I would be nice to be able to change collator without unstaking.

@snoopy1412 please check this.

**Comment by 1022ranji** [comment]
@2xJDubs It looks like it was a crab indexing issue, it has been reindexed and you can do an unstake operation to see if the problem still exists.

**Comment by 2xJDubs** [comment]
> @2xJDubs It looks like it was a crab indexing issue, it has been reindexed and you can do an unstake operation to see if the problem still exists.

@1022ranji I tested again and same issue.  Still not getting a txn approval popup from my wallet.

**Comment by 1022ranji** [comment]
> > @2xJDubs It looks like it was a crab indexing issue, it has been reindexed and you can do an unstake operation to see if the problem still exists.
> 
> @1022ranji I tested again and same issue. Still not getting a txn approval popup from my wallet.

Last night, the indexing got stuck during a reorg on the Crab network, which caused your unstaking to fail. Yalin redeployed it, and it should be working normally now. However, there is still a chance that the indexing issue might happen again. They are currently considering how to fully resolve this problem.

**Comment by 2xJDubs** [comment]
Just tested again and this time it worked.  The latest fix may have helped.
